language: node_js
sudo: false
node_js:
  - 8
  - 6

before_install:
  - npm install npm@latest -g
  - npm install greenkeeper-lockfile@1 -g

before_script:
  - greenkeeper-lockfile-update
script:
  - npm test
after_script:
  - greenkeeper-lockfile-upload
